### PR TITLE
Add tqdm to dependencies

### PR DESCRIPTION
**Pull request by betatim**
Hi there 👋!

I was looking at the notebooks you made to use them for a short demo during a talk about making collaborating between scientists easier. One of the notebooks raised an error because tqdm wasn't installed so this PR adds that.

Testing this now.

### CODE REVIEW

**Comment by lheagy** [comment]
Excellent, many thanks @betatim! If you are willing to share some info on your presentation, it would be great to see how you are using it! 

@fourndo, would you be willing to take a look at this pr?

**Comment by betatim** [comment]
I will either use this repo as an example of "making it easier to collaborate between people working on the same project" (use case kinda thing at the start of the workshop) and/or maybe as an example for people to explore further and base their own things on.

The workshop will be about Binder at http://osip2019.epfl.ch/

**Comment by fourndo** [comment]
Hi @betatim, thanks for this.
I am ok with the change, but it would be good to know where exactly it crashed. 
I am not sure why ``tqdm`` gets called here, we are not using anywhere in the library. I am guessing it is from another package. 
Would you mind posting your error log?

**Comment by fourndo** [comment]
I am actually to know that it exists. I will definitely make use of it.

**Comment by betatim** [comment]
I clicked the binder badge on http://toolkit.geosci.xyz/content/apps.html and then the `2_2_1_Search_Mag_Data_Visualization.ipynb` notebook. If I run the first cell I get this:
```python
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-2d9f630fe0eb> in <module>
      1 ## Load all libraries and setup the synthetic problem
----> 2 from GeoToolkit.Mag import Simulator, DataIO
      3 dataGrid = DataIO.loadGeoTiffFile("./assets/Search/MAG_UTM09.tiff")

/srv/conda/envs/notebook/lib/python3.6/site-packages/GeoToolkit/__init__.py in <module>
----> 1 from . import Mag
      2 from . import graphics
      3 
      4 
      5 __version__ = '0.0.1'

/srv/conda/envs/notebook/lib/python3.6/site-packages/GeoToolkit/Mag/__init__.py in <module>
      1 from . import Mag
----> 2 from . import Simulator
      3 from . import ProblemSetter
      4 from . import MathUtils
      5 from . import DataIO

/srv/conda/envs/notebook/lib/python3.6/site-packages/GeoToolkit/Mag/Simulator.py in <module>
      1 from . import Mag
      2 from . import MathUtils
----> 3 from . import DataIO
      4 from . import ProblemSetter
      5 import re

/srv/conda/envs/notebook/lib/python3.6/site-packages/GeoToolkit/Mag/DataIO.py in <module>
     14 import fiona
     15 from fiona.crs import from_epsg
---> 16 from download import download
     17 import ipywidgets as widgets
     18 import shapefile

/srv/conda/envs/notebook/lib/python3.6/site-packages/download/__init__.py in <module>
      1 """A tiny module to make downloading with python super easy."""
----> 2 from .download import download
      3 
      4 __version__ = "0.3.4"

/srv/conda/envs/notebook/lib/python3.6/site-packages/download/download.py in <module>
     14 import ftplib
     15 from functools import partial
---> 16 from tqdm import tqdm
     17 
     18 if sys.version_info[0] == 3:

ModuleNotFoundError: No module named 'tqdm'
```

and upon (actually) reading the traceback I think the problem is that https://github.com/choldgraf/download by a certain @choldgraf (👋) seems to be using it but doesn't(?) declare it as a dependency. So maybe the right place to fix this is there and not here.

**Comment by choldgraf** [comment]
oh nooo - ok I'll update that :-)  I had no idea people used that tool :-P  PRs are welcome there too Tim!!!!

**Pull request merged**
